package com.github.libretube.test.ui.theme

import androidx.compose.ui.graphics.Color

// Default "Blue" Light Theme Colors
val BlueLightPrimary = Color(0xFF0058CB)
val BlueLightOnPrimary = Color(0xFFFFFFFF)
val BlueLightPrimaryContainer = Color(0xFFD9E2FF)
val BlueLightOnPrimaryContainer = Color(0xFF001945)
val BlueLightSecondary = Color(0xFF575E71)
val BlueLightOnSecondary = Color(0xFFFFFFFF)
val BlueLightSecondaryContainer = Color(0xFFDCE2F9)
val BlueLightOnSecondaryContainer = Color(0xFF141B2C)
val BlueLightTertiary = Color(0xFF725572)
val BlueLightOnTertiary = Color(0xFFFFFFFF)
val BlueLightTertiaryContainer = Color(0xFFFDD7FA)
val BlueLightOnTertiaryContainer = Color(0xFF2A132C)
val BlueLightError = Color(0xFFBA1A1A)
val BlueLightErrorContainer = Color(0xFFFFDAD6)
val BlueLightOnError = Color(0xFFFFFFFF)
val BlueLightOnErrorContainer = Color(0xFF410002)
val BlueLightBackground = Color(0xFFFEFBFF)
val BlueLightOnBackground = Color(0xFF1B1B1F)
val BlueLightSurface = Color(0xFFFEFBFF)
val BlueLightOnSurface = Color(0xFF1B1B1F)
val BlueLightSurfaceVariant = Color(0xFFE1E2EC)
val BlueLightOnSurfaceVariant = Color(0xFF44464F)
val BlueLightOutline = Color(0xFF757780)

// Default "Blue" Dark Theme Colors
val BlueDarkPrimary = Color(0xFFB0C6FF)
val BlueDarkOnPrimary = Color(0xFF002D6F)
val BlueDarkPrimaryContainer = Color(0xFF00429B)
val BlueDarkOnPrimaryContainer = Color(0xFFD9E2FF)
val BlueDarkSecondary = Color(0xFFC0C6DC)
val BlueDarkOnSecondary = Color(0xFF293042)
val BlueDarkSecondaryContainer = Color(0xFF404659)
val BlueDarkOnSecondaryContainer = Color(0xFFDCE2F9)
val BlueDarkTertiary = Color(0xFFE0BBDD)
val BlueDarkOnTertiary = Color(0xFF412742)
val BlueDarkTertiaryContainer = Color(0xFF593D5A)
val BlueDarkOnTertiaryContainer = Color(0xFFFDD7FA)
val BlueDarkError = Color(0xFFFFB4AB)
val BlueDarkErrorContainer = Color(0xFF93000A)
val BlueDarkOnError = Color(0xFF690005)
val BlueDarkOnErrorContainer = Color(0xFFFFDAD6)
val BlueDarkBackground = Color(0xFF1B1B1F)
val BlueDarkOnBackground = Color(0xFFE3E2E6)
val BlueDarkSurface = Color(0xFF1B1B1F)
val BlueDarkOnSurface = Color(0xFFE3E2E6)
val BlueDarkSurfaceVariant = Color(0xFF44464F)
val BlueDarkOnSurfaceVariant = Color(0xFFC5C6D0)
val BlueDarkOutline = Color(0xFF8F9099)
